eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka'
    
feign:
  client:
    config:
      default:
        readTimeout: '5000'
        loggerLevel: FULL
    persons:
      name: PERSONA-SERVICE
      uri: /api/v2/example  
      get: /get-persons
      post: /save-person
      put: /update-person
      delete: /delete-person

server:
  port: 9095
  
spring:
  application:
    name: PERSONA-CLIENT